bokulich-lab/RESCRIPt

- README.md
- rescript/cross_validate.py
- rescript/plugin_setup.py
A few minor tweaks:
* fix + enrich installation instructions in readme
* cite general zenodo DOI + badge (instead of release-specific DOI)
* drop `random_state` from `evaluate_fit_classifier` — it is not used if there is no CV!
> generalize doi etc

- rescript/evaluate.py
- rescript/tests/data/real-taxa-test.tsv
- rescript/tests/test_evaluate.py
Fixes a few minor bugs in `evaluate_taxonomy`. These came to light when testing on the UNITE taxonomy — this method was originally validated using greengenes/silva style taxonomies, but testing on UNITE (which has taxonomies like `k__unidentified;p__unidentified;...` a few issues became apparent:
1. redundant taxonomies were not being counted correctly, because the rank depth was counted after casting to a `set`
2. taxonomies without annotation at ANY level were being miscounted (they were counted as classified as the base level, but they are not!)
3. entropy was incorrectly counted if unique counts 
This PR fixes these issues in a few ways:
1. adds some real taxa strings as test data, including UNITE, GG, SILVA, and old-style SILVA. We can add to this list as we test new data sources.
2. …
> fix taxonomy eval

- rescript/cross_validate.py
- rescript/plugin_setup.py
- rescript/tests/test_cross_validate.py
e-c-v previously output expected + observed taxonomies. It is already a pipeline — so why not also output a visualization of accuracy results?
This PR adds `evaluate-classifications` to the `evaluate-cross-validate` pipeline so that a visualization of accuracy results is output along with observed/expected results.
> add evaluate-classifications to evaluate-cross-validate pipeline

- rescript/cross_validate.py
- rescript/dereplicate.py
fixes #18
replaces pandas with skbio for subsetting large sequence sets. skbio is now used for all sequence processing.
in the process of looking for other places where pandas is used for handing seqs, I found some misleading outdated docstrings in `cross_validate.py` so edited these comments. 
So far it looks like swapping this out did not lead to any real performance improvements (tested dereplicating a large set of sequences) but I did not check memory usage, and the code looks cleaner now without inline artifact imports!
> refactor dereplicate to use skbio for seq subsetting

- rescript/_utilities.py
- rescript/merge.py
- rescript/plugin_setup.py
- rescript/tests/test_merge.py
`merge_taxa` has two new modes:
1. `majority` performs LCA merging, with priority to majority labels
2. `super` performs LCA merging, with priority to majority labels. Labels that are substrings of other labels (including empty rank handles) are collapsed prior to majority/LCA.
In general also includes a decent code refactor and addition of several more tests.
> add super LCA and majority LCA merging

- rescript/dereplicate.py
- rescript/plugin_setup.py
- rescript/tests/test_derep.py
Adds the same "super"  mode of `merge_taxa` to `dereplicate` for taxonomy dereplication. Help text was updated and two tests cases added.
> IMP: adds super to dereplicate

- rescript/filter_length.py
- rescript/plugin_setup.py
- rescript/tests/test_filter_length.py
allows filtering a `FeatureData[Taxonomy]` artifact based on one or more search criteria.
I decided to add this because, while Q2 style is to typically just subset taxonomy, RESCRIPt evaluate taxonomy methods sometimes require taxonomy to be subset (e.g., if evaluating a specific clade, and some methods do not allow superset taxonomies, e.g.,` evaluate-classifications`)
> added filter-taxa method

- rescript/get_data.py
- rescript/plugin_setup.py
- rescript/tests/test_get_data.py
Adds the ability to fetch LSURef and LSURef_NR99 from Silva 138.1.
Fixes issue #97
> added LSU-138 to get-silva-data

- README.md
Sets minimum QIIME 2 version to `2021.2`. Fixes #98 
Is there anything else that we should add / change within docs of this PR?
> issue-98 : updated minimum qiime 2 version in docs

- rescript/merge.py
- rescript/plugin_setup.py
- rescript/tests/test_merge.py
This PR introduces a fix to replace empty taxonomy strings (resulting from unresolved taxonomies) with 'Unassigned' label to prevent downstream issues with the resulting taxonomy (e.g. the pd.DataFrame -> TSVTaxonomyFormat transformer will turn those into NaN values)  
Closes #111.
> BUG: set unresolved taxonomies to 'Unassigned'

- rescript/_utilities.py
- rescript/merge.py
- rescript/tests/test_merge.py
When the DataFrames get _combined_ the columns will be sorted alphabetically, with the preference to first sort the capitalized column names and only then the other ones. That causes the column 'Taxa' to loose its position as a first column (required) when the other column names were provided as capitalized words.
Changes introduced in this PR allow to first capitalize all the column names to ensure consistent sorting behaviour during merge and then ensure that the 'Taxon' column is always first, regardless of the other columns. The tests were adjusted to reflect this behaviour.
Closes #112.
> BUG: fix 'Taxon' column to always be first after merge

- README.md
- rescript/citations.bib
- rescript/plugin_setup.py
Updates the RESCRIPt citation from the [bioRxiv preprint](https://doi.org/10.1101/2020.10.05.326504), to the recently accepted peer reviewed version at [PLoS Computational Biology](https://doi.org/10.1371/journal.pcbi.1009581).
> update rescript citation to PLoS Comp Bio

- README.md
This PR updates the README:
- Minimum version of QIIME 2 is now `2022.8`
- Added link to the new [Using RESCRIPt's 'extract-seq-segments' to extract reference sequences without PCR primer pairs.](https://forum.qiime2.org/t/using-rescripts-extract-seq-segments-to-extract-reference-sequences-without-pcr-primer-pairs/23618) tutorial.
- Added link to the related [db-benchmarks-2020 repo](https://github.com/bokulich-lab/db-benchmarks-2020).
> update readme for q2-2022.8

- ci/recipe/meta.yaml
- rescript/ncbi.py
Address issue #143. Specifically, these changes were applied:
- for `ncbi.py`:
-  The import statement `from joblib.externals.loky.backend.managers import LokyManager` had been replaced with `from multiprocessing import Manager`, along with associated code changes
- for `meta.yaml`:
- `joblib 1.1` pin was removed
> DEP: Fix joblib for ncbi.py

- rescript/orient.py
This PR adds a future deprecation warning for the parameters `perc_identity`, `query_cov` and `left_justify` in the function `orient-seqs`. See [PR #149](https://github.com/bokulich-lab/RESCRIPt/pull/149) for more details.
> MAINT: Add future deprecation warning for orient-seqs

- rescript/orient.py
- rescript/plugin_setup.py
- rescript/tests/test_orient.py
This PR replaces `vsearch --usearch_global` with `vsearch --orient`, which is more efficient (closes #146). Additionally, it removes the deprecation warning inserted in version `2023.2` (closes #151).
Some parameters were removed since they are not supported with `--orient`:
- `--id`
- `--maxaccepts`
- `--strand`
- `--query_cov`
- `--userfields`
- `--leftjust`
However, optional parametes available with `--orient` were added:
- `--dbmask`
- `--relabel`
- `--relabel_keep`
- `--relabel_md5`
- `--relabel_self`
- `--sizein`
- `--sizeout`
> MAINT: update `orient-seqs` to use vsearch `orient`

- ci/recipe/meta.yaml
Turns out this is causing some issues with conda and matplotlib that don't really _need_ to be an issue right now.
https://github.com/qiime2/distributions/actions/runs/6385353574/job/17331623684?pr=27
This isn't an issue with the amplicon distro for whatever reason, but we haven't looked into it too closely yet.
Related to #163
> DEP: drop q2-longitudinal

- rescript/citations.bib
I had to update these citations to meet the Sphinx build requirements in order to get our docs build working with RESCRIPt in the amplicon distro.
Here are the papers I referenced when making these changes:
https://academic.oup.com/nar/article/46/D1/D8/4621330#authorNotesSectionTitle
https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1009581
> DOC: fixes citation formatting reqs for sphinx docs builds

- .github/workflows/ci-dev.yaml
Updates the distro label to 'amplicon' so that ci-dev actions are running against the correct metapackage environment.
> CI: shotgun to amplicon

- ci/recipe/meta.yaml
this needs to be added so that the unit test suite actually runs for all CI actions (ci-dev, prepare, release, etc)
> CI: adds command to run tests

- rescript/plugin_setup.py
- rescript/trim_alignment.py
Fixes #127 
Also, made some minor help text and documentation edits.
> ENH: adds `--p-n-threads` option to `trim-alignment`

- rescript/get_gtdb.py
- rescript/plugin_setup.py
- rescript/tests/test_get_gtdb.py
Resolves issue #183.
Also includes a refactor of some code... That is, GTDB v220 now hosts the FASTA files as `fna.gz`, while files for the older versions of the database continue to be hosted as `tar.gz`.
> ENH: Adds ability to fetch GTDB v220 to get-gtdb-data

- rescript/get_data.py
- rescript/plugin_setup.py
Addresses #196 
SILVA recently put out a [maintenance release centering on taxonomy](https://www.arb-silva.de/news/view/2024/07/11/silva-release-1382/). This constitutes [version 132](https://www.arb-silva.de/no_cache/download/archive/release_138_2/).
I've added the ability to automatically download both the SSU and LSU files within `get-silva-data`.
> ENH: Adds SILVA 138.2

- rescript/tests/test_ncbi.py
Addresses the latest [amplicon prepare failure](https://github.com/qiime2/distributions/actions/runs/11197922773/job/31251433278?pr=406#step:9:208) due to an apparent change in the GH runner's log formatting. `Retrying` is now present on the third line of the log, instead of the first line.
> TEST: fixes test failure due to updated GH runner log formatting

- ci/recipe/meta.yaml
- rescript/cross_validate.py
- rescript/evaluate.py
- rescript/plugin_setup.py
- rescript/tests/test_cross_validate.py
Closes https://github.com/qiime2/q2-vizard/issues/32
This PR will replace the use of `longitudinal volatility` with the new lineplot that's now available within q2-vizard. The following visualizers will receive this replacement:
- evaluate-classifications
- evaluate-taxonomy
> IMP: replace volatility with lineplot for `evaluate_*` visualizers

- rescript/ncbi_datasets.py
- rescript/plugin_setup.py
- rescript/tests/test_ncbi_datasets.py
solves #194 
- Added ranks and rank-propagation parameters to `get-ncbi-genomes`.
- The parameters behave the same as in the `get-ncbi-data` function
> ENH: Added ranks and rank-propagation parameters to `get-ncbi-genomes`

- rescript/get_unite.py
- rescript/plugin_setup.py
- rescript/tests/test_get_unite.py
Addresses #216.
Replaces version, *e.g.* `10.0` with the latest release date `2025-02-19` (and doi) for that version.
> ENH: updating version number with release date

- rescript/get_gtdb.py
- rescript/plugin_setup.py
> ENH: adds GTDB `226.0` to list of downloadable reference files.

- rescript/get_gtdb.py
- rescript/plugin_setup.py
- rescript/tests/test_get_gtdb.py
Fixes #228.
If downloads from the primary GTDB host site are slow, *i.e.* `--p-url-type 'Primary'`, user can switch to using the GTDB mirror site by using `--p-url-type 'Mirror'`
> ENHL adds ability to toggle GTDB download url.

- rescript/get_midori2.py
- rescript/plugin_setup.py
- rescript/tests/test_get_midori2.py
This PR is simply adding the recent `GenBank266_2025-04-24` & `GenBank267_2025-06-19` MIDORI2 databases available from [here](https://www.reference-midori.info/download.php).
I also fixed a typo in `test_get_midori2.py`.
*If this passes the GitHub checks I'll merge, as there is no new code to be reviewed.*
> ENH: adding new DBs to `get-midori2-data`
